version: '3'

services:
  nginx: # тут я создаю контейнер с nginx, он просто принимает запросы и перенаправляет в php
    image: nginx:stable-alpine # образ на основе которого создаю (stable-alpine просто весит меньше)
    ports: # связываю порты
      - 3000:80 # тут можно любые указать, какие удобно, на левые по итогу нужо будет слать запросы, а правы нужно будет указать в конфиге nginx
    volumes: # свызываю папки
      - ./:/var/www/full # папка где лежит бэк с папкой в контейнере
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # тут слева путь до конфига, справа всегда такой путь, это дефолтное местоположение конфига
    depends_on: # указываю поле каких контейнеров создастся этот
      - php
      - database

  php: # контейнер с php
    build: # поскольку я не использую дефолтный образ
      context: ./ # указываю путь до Dockerfile
    volumes:
      - ./:/var/www/full # связываю папку с проектом с папкой в php (она должна совпадать с папкой в nginx)
    depends_on: # запускаю после бд
      - database

  database: # ну тут то же самое
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 7:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth2.0

    volumes:
      - ./mysql:/var/lib/mysql
