<?php

namespace ContainerFPtPMHf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KOo0DbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kOo_0Db' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kOo_0Db'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'task' => ['privates', '.errored..service_locator.kOo_0Db.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.kOo_0Db": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'security' => '?',
            'task' => 'App\\Entity\\Task',
        ]);
    }
}
