<?php

namespace ContainerGMaEg4F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MSuYKEyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.mSuYKEy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mSuYKEy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\TaskController::__invoke' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Controller\\TaskControllerEmail::__invoke' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\TaskControllerId::__invoke' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\TaskStatus::__invoke' => ['privates', '.service_locator.kOo_0Db', 'get_ServiceLocator_KOo0DbService', true],
            'App\\Controller\\User\\RegistrationController::__invoke' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\TaskController:__invoke' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Controller\\TaskController' => ['privates', '.service_locator.ATt7aga', 'get_ServiceLocator_ATt7agaService', true],
            'App\\Controller\\TaskControllerEmail:__invoke' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\TaskControllerEmail' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\TaskControllerId:__invoke' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\TaskControllerId' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\TaskStatus:__invoke' => ['privates', '.service_locator.kOo_0Db', 'get_ServiceLocator_KOo0DbService', true],
            'App\\Controller\\TaskStatus' => ['privates', '.service_locator.kOo_0Db', 'get_ServiceLocator_KOo0DbService', true],
            'App\\Controller\\User\\RegistrationController:__invoke' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\User\\RegistrationController' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\TaskController::__invoke' => '?',
            'App\\Controller\\TaskControllerEmail::__invoke' => '?',
            'App\\Controller\\TaskControllerId::__invoke' => '?',
            'App\\Controller\\TaskStatus::__invoke' => '?',
            'App\\Controller\\User\\RegistrationController::__invoke' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\TaskController:__invoke' => '?',
            'App\\Controller\\TaskController' => '?',
            'App\\Controller\\TaskControllerEmail:__invoke' => '?',
            'App\\Controller\\TaskControllerEmail' => '?',
            'App\\Controller\\TaskControllerId:__invoke' => '?',
            'App\\Controller\\TaskControllerId' => '?',
            'App\\Controller\\TaskStatus:__invoke' => '?',
            'App\\Controller\\TaskStatus' => '?',
            'App\\Controller\\User\\RegistrationController:__invoke' => '?',
            'App\\Controller\\User\\RegistrationController' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
