<?php

namespace ContainerGMaEg4F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeague_Oauth2Server_Grant_AuthCodeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'league.oauth2_server.grant.auth_code' shared service.
     *
     * @return \League\OAuth2\Server\Grant\AuthCodeGrant
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/league/event/src/EmitterAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server/src/Grant/GrantTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/event/src/EmitterAwareTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server/src/CryptTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server/src/Grant/AbstractGrant.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server/src/Grant/AbstractAuthorizeGrant.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server/src/Grant/AuthCodeGrant.php';

        $container->privates['league.oauth2_server.grant.auth_code'] = $instance = new \League\OAuth2\Server\Grant\AuthCodeGrant(($container->privates['league.oauth2_server.repository.auth_code'] ?? $container->load('getLeague_Oauth2Server_Repository_AuthCodeService')), ($container->privates['league.oauth2_server.repository.refresh_token'] ?? $container->load('getLeague_Oauth2Server_Repository_RefreshTokenService')), new \DateInterval('PT10M'));

        $instance->setRefreshTokenTTL(new \DateInterval('P1M'));

        return $instance;
    }
}
