<?php

namespace ContainerGMaEg4F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeague_Oauth2Server_Manager_InMemory_ScopeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'league.oauth2_server.manager.in_memory.scope' shared service.
     *
     * @return \League\Bundle\OAuth2ServerBundle\Manager\InMemory\ScopeManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server-bundle/src/Manager/ScopeManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server-bundle/src/Manager/InMemory/ScopeManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server-bundle/src/ValueObject/Scope.php';

        $container->privates['league.oauth2_server.manager.in_memory.scope'] = $instance = new \League\Bundle\OAuth2ServerBundle\Manager\InMemory\ScopeManager(NULL);

        $instance->save(new \League\Bundle\OAuth2ServerBundle\ValueObject\Scope('ROLE_USER'));

        return $instance;
    }
}
