<?php

namespace ContainerGMaEg4F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeague_Oauth2Server_EmitterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'league.oauth2_server.emitter' shared service.
     *
     * @return \League\Event\Emitter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/league/event/src/ListenerAcceptorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/event/src/EmitterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/event/src/Emitter.php';

        $container->privates['league.oauth2_server.emitter'] = $instance = new \League\Event\Emitter();

        $instance->useListenerProvider(($container->privates['league.oauth2_server.symfony_league_listener_provider'] ?? $container->load('getLeague_Oauth2Server_SymfonyLeagueListenerProviderService')));

        return $instance;
    }
}
