<?php

namespace ContainerGMaEg4F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeague_Oauth2Server_Factory_AuthorizationRequestResolveEventService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'league.oauth2_server.factory.authorization_request_resolve_event' shared service.
     *
     * @return \League\Bundle\OAuth2ServerBundle\Event\AuthorizationRequestResolveEventFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server-bundle/src/Event/AuthorizationRequestResolveEventFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server-bundle/src/Converter/ScopeConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server-bundle/src/Converter/ScopeConverter.php';

        return $container->privates['league.oauth2_server.factory.authorization_request_resolve_event'] = new \League\Bundle\OAuth2ServerBundle\Event\AuthorizationRequestResolveEventFactory(($container->privates['league.oauth2_server.converter.scope'] ??= new \League\Bundle\OAuth2ServerBundle\Converter\ScopeConverter()), ($container->privates['league.oauth2_server.manager.in_memory.client'] ?? $container->load('getLeague_Oauth2Server_Manager_InMemory_ClientService')));
    }
}
