<?php

namespace ContainerGMaEg4F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeague_Oauth2Server_Factory_HttpFoundationService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'league.oauth2_server.factory.http_foundation' shared service.
     *
     * @return \Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/psr-http-message-bridge/HttpFoundationFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/psr-http-message-bridge/Factory/HttpFoundationFactory.php';

        return $container->privates['league.oauth2_server.factory.http_foundation'] = new \Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory();
    }
}
