<?php

namespace ContainerGMaEg4F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeague_Oauth2Server_AuthorizationServer_GrantConfiguratorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'league.oauth2_server.authorization_server.grant_configurator' shared service.
     *
     * @return \League\Bundle\OAuth2ServerBundle\AuthorizationServer\GrantConfigurator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/league/oauth2-server-bundle/src/AuthorizationServer/GrantConfigurator.php';

        return $container->privates['league.oauth2_server.authorization_server.grant_configurator'] = new \League\Bundle\OAuth2ServerBundle\AuthorizationServer\GrantConfigurator(new RewindableGenerator(function () use ($container) {
            return new \EmptyIterator();
        }, 0));
    }
}
