<?php

namespace ContainerGMaEg4F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_ApiTokenService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.api_token' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        return $container->privates['security.firewall.map.config.api_token'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('api_token', 'security.user_checker', '.security.request_matcher.pu7NcaE', false, false, NULL, NULL, NULL, NULL, NULL, [], NULL, NULL);
    }
}
