<?php

namespace Proxies\__CG__\League\Bundle\OAuth2ServerBundle\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \League\Bundle\OAuth2ServerBundle\Model\Client implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'identifier' => [parent::class, 'identifier', null],
        "\0".'League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient'."\0".'active' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'active', null],
        "\0".'League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient'."\0".'allowPlainTextPkce' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'allowPlainTextPkce', null],
        "\0".'League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient'."\0".'grants' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'grants', null],
        "\0".'League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient'."\0".'name' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'name', null],
        "\0".'League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient'."\0".'redirectUris' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'redirectUris', null],
        "\0".'League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient'."\0".'scopes' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'scopes', null],
        "\0".'League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient'."\0".'secret' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'secret', null],
        'active' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'active', null],
        'allowPlainTextPkce' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'allowPlainTextPkce', null],
        'grants' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'grants', null],
        'identifier' => [parent::class, 'identifier', null],
        'name' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'name', null],
        'redirectUris' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'redirectUris', null],
        'scopes' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'scopes', null],
        'secret' => ['League\\Bundle\\OAuth2ServerBundle\\Model\\AbstractClient', 'secret', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".'*'."\0".'identifier' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
