<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGMaEg4F\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGMaEg4F/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerGMaEg4F.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerGMaEg4F\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerGMaEg4F\App_KernelTestDebugContainer([
    'container.build_hash' => 'GMaEg4F',
    'container.build_id' => '76ade594',
    'container.build_time' => 1681330904,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGMaEg4F');
